package configurafacil.presentation;

import configurafacil.business.ConfiguraFacil;
import java.awt.Frame;
/**
 *
 * @author Todos
 */
public class ConfigurarInteriorGUI extends javax.swing.JFrame {
    
    private Frame frAnterior;
    private ConfiguraFacil facade;
    /**
     * Creates new form Modelo
     */
    public ConfigurarInteriorGUI(Frame fr, ConfiguraFacil facade) {
        frAnterior=fr;
        this.facade=facade;
        initComponents();
        predefinicoes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSeguinte = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        imgLogotipo = new javax.swing.JLabel();
        labelTitulo1 = new javax.swing.JLabel();
        labelTitulo2 = new javax.swing.JLabel();
        labelTituloFinal = new javax.swing.JLabel();
        imgBola1 = new javax.swing.JLabel();
        imgBola2 = new javax.swing.JLabel();
        boxEstofos = new javax.swing.JComboBox<>();
        boxFrisos = new javax.swing.JComboBox<>();
        boxLuzes = new javax.swing.JComboBox<>();
        labelTitulo3 = new javax.swing.JLabel();
        imgBola3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Configuração Interior");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        btnSeguinte.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        btnSeguinte.setText("Seguinte");
        btnSeguinte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeguinteActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        imgLogotipo.setFont(new java.awt.Font("Segoe UI Semibold", 0, 36)); // NOI18N
        imgLogotipo.setForeground(new java.awt.Color(28, 91, 122));
        imgLogotipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/configurafacil/presentation/Imagens/Logótipo.png"))); // NOI18N

        labelTitulo1.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        labelTitulo1.setForeground(new java.awt.Color(0, 44, 148));
        labelTitulo1.setText("Escolha os Estofos");

        labelTitulo2.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        labelTitulo2.setForeground(new java.awt.Color(0, 44, 148));
        labelTitulo2.setText("Escolha os Frisos");

        labelTituloFinal.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        labelTituloFinal.setText("Configuração do Exterior: Seguinte");

        imgBola1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/configurafacil/presentation/Imagens/One.png"))); // NOI18N

        imgBola2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/configurafacil/presentation/Imagens/Two.png"))); // NOI18N

        boxEstofos.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        boxEstofos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Estofo Tecido Preto  - 0,00€ ", "Estofo Pele Preto - 1.255,00€", "Estofo Sport Cinzento  - 1.765,00€", "Estofo Pele Camel - 1.855,00€" }));
        boxEstofos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxEstofosActionPerformed(evt);
            }
        });

        boxFrisos.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        boxFrisos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Frisos em Prata - 0,00€", "Frisos Preto Brilhante - 170,00€", "Frisos Pérola Cromado - 180,00€", "Frisos Liga de Carbono - 200,00€" }));
        boxFrisos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxFrisosActionPerformed(evt);
            }
        });

        boxLuzes.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        boxLuzes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Luzes Normais Brancas - 0,00€", "Luzes Azul - 115,00€", "Luzes Personalizáveis - 155,00€", "Luzes Vermelhas - 170,00€" }));
        boxLuzes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxLuzesActionPerformed(evt);
            }
        });

        labelTitulo3.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        labelTitulo3.setForeground(new java.awt.Color(0, 44, 148));
        labelTitulo3.setText("Escolha as Luzes");

        imgBola3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/configurafacil/presentation/Imagens/Three.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSeguinte)
                        .addGap(105, 105, 105))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(imgLogotipo)
                        .addGap(30, 30, 30))))
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(imgBola1)
                            .addGap(215, 215, 215))
                        .addComponent(labelTitulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(labelTituloFinal))
                            .addComponent(boxEstofos, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(boxFrisos, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(boxLuzes, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(imgBola2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(labelTitulo2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(imgBola3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(labelTitulo3, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jSeparator1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(imgLogotipo, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelTitulo1))
                    .addComponent(imgBola1))
                .addGap(18, 18, 18)
                .addComponent(boxEstofos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(labelTitulo2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(imgBola2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addComponent(boxFrisos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imgBola3)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(labelTitulo3)))
                .addGap(18, 18, 18)
                .addComponent(boxLuzes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(labelTituloFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSeguinte)
                    .addComponent(btnCancelar))
                .addGap(30, 30, 30))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void boxFrisosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxFrisosActionPerformed

        String escolha =  (String) boxFrisos.getSelectedItem();
        facade.escolheFrisos(escolha);
    }//GEN-LAST:event_boxFrisosActionPerformed

    private void boxLuzesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxLuzesActionPerformed

        String escolha =  (String) boxLuzes.getSelectedItem();
        facade.escolheLuzes(escolha);
    }//GEN-LAST:event_boxLuzesActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        frAnterior.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnSeguinteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeguinteActionPerformed
        ConfigurarExteriorGUI nova = new ConfigurarExteriorGUI(this,facade);
        nova.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnSeguinteActionPerformed

    private void boxEstofosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxEstofosActionPerformed
        String escolha = (String) boxEstofos.getSelectedItem();
        facade.escolheEstofos(escolha);
    }//GEN-LAST:event_boxEstofosActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        frAnterior.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    private void predefinicoes() {
       boxEstofos.setSelectedIndex(0);
       boxFrisos.setSelectedIndex(0);
       boxLuzes.setSelectedIndex(0);
   }
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxEstofos;
    private javax.swing.JComboBox<String> boxFrisos;
    private javax.swing.JComboBox<String> boxLuzes;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSeguinte;
    private javax.swing.JLabel imgBola1;
    private javax.swing.JLabel imgBola2;
    private javax.swing.JLabel imgBola3;
    private javax.swing.JLabel imgLogotipo;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelTitulo1;
    private javax.swing.JLabel labelTitulo2;
    private javax.swing.JLabel labelTitulo3;
    private javax.swing.JLabel labelTituloFinal;
    // End of variables declaration//GEN-END:variables
}
