package configurafacil.presentation;

import configurafacil.business.ConfiguraFacil;
import java.awt.Frame;

/**
 *
 * @author Todos
 */
public class ConfigurarExteriorGUI extends javax.swing.JFrame {
    
    private Frame frAnterior;
    private ConfiguraFacil facade;
    /**
     * Creates new form Modelo
     */
    public ConfigurarExteriorGUI(Frame fr, ConfiguraFacil facade) {
        frAnterior=fr;
        this.facade=facade;
        initComponents();
        predefinicoes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinner1 = new javax.swing.JSpinner();
        btnSeguinte = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        imgLogotipo = new javax.swing.JLabel();
        labelTitulo1 = new javax.swing.JLabel();
        labelTitulo2 = new javax.swing.JLabel();
        imgBola1 = new javax.swing.JLabel();
        imgBola2 = new javax.swing.JLabel();
        boxParaChoques = new javax.swing.JComboBox<>();
        boxTetos = new javax.swing.JComboBox<>();
        boxVidros = new javax.swing.JComboBox<>();
        labelTitulo3 = new javax.swing.JLabel();
        imgBola3 = new javax.swing.JLabel();
        boxPneus = new javax.swing.JComboBox<>();
        labelTitulo4 = new javax.swing.JLabel();
        imgBola4 = new javax.swing.JLabel();
        boxJantes = new javax.swing.JComboBox<>();
        labelTituloFinal = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Configuração Exterior");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        btnSeguinte.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        btnSeguinte.setText("Seguinte");
        btnSeguinte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeguinteActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        imgLogotipo.setFont(new java.awt.Font("Segoe UI Semibold", 0, 36)); // NOI18N
        imgLogotipo.setForeground(new java.awt.Color(28, 91, 122));
        imgLogotipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/configurafacil/presentation/Imagens/Logótipo.png"))); // NOI18N

        labelTitulo1.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        labelTitulo1.setForeground(new java.awt.Color(0, 44, 148));
        labelTitulo1.setText("Escolha o Pára-Choque");

        labelTitulo2.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        labelTitulo2.setForeground(new java.awt.Color(0, 44, 148));
        labelTitulo2.setText("Escolha o Teto");

        imgBola1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/configurafacil/presentation/Imagens/One.png"))); // NOI18N

        imgBola2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/configurafacil/presentation/Imagens/Two.png"))); // NOI18N

        boxParaChoques.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        boxParaChoques.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pára-Choque Básico - 0,00€", "Pára-Choque Linha Comfort - 1.559,00€", "Pára-Choque Linha Sport - 1.869,00€" }));
        boxParaChoques.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxParaChoquesActionPerformed(evt);
            }
        });

        boxTetos.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        boxTetos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Teto Normal - 0,00€", "Teto de Abrir em Tecido - 1.630,00€", "Teto Panorâmico - 1.755,00€", "Teto de Abrir Automático - 1,950,00€" }));
        boxTetos.setToolTipText("");
        boxTetos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxTetosActionPerformed(evt);
            }
        });

        boxVidros.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        boxVidros.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Vidro Normal - 0,00 €", "Vidro Escurecido - 2.069,00€" }));
        boxVidros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxVidrosActionPerformed(evt);
            }
        });

        labelTitulo3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        labelTitulo3.setForeground(new java.awt.Color(0, 44, 148));
        labelTitulo3.setText("Escolha os Vidros");

        imgBola3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/configurafacil/presentation/Imagens/Three.png"))); // NOI18N

        boxPneus.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        boxPneus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pneu Continental - 0,00€", "Pneu Michelin - 1.555,00€" }));
        boxPneus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxPneusActionPerformed(evt);
            }
        });

        labelTitulo4.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        labelTitulo4.setForeground(new java.awt.Color(0, 44, 148));
        labelTitulo4.setText("Escolha os Pneus/Jantes");

        imgBola4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/configurafacil/presentation/Imagens/Four.png"))); // NOI18N

        boxJantes.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        boxJantes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jantes Normais - 0,00€", "Jantes em Preto - 745,00€", "Jantes Liga-Leve Ferric - 856,00€", "Jantes Bicolores em Preto - 945,00€" }));
        boxJantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxJantesActionPerformed(evt);
            }
        });

        labelTituloFinal.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        labelTituloFinal.setText("Efetuar Pagamento: Seguinte");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(imgBola4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelTitulo4))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSeguinte)
                        .addGap(24, 24, 24)))
                .addGap(84, 84, 84))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(boxPneus, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boxJantes, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(boxParaChoques, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(boxTetos, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(boxVidros, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(imgBola1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(labelTitulo1))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(imgBola2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(labelTitulo2))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(imgBola3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(labelTitulo3))))
                .addGap(45, 45, 45))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(imgLogotipo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(labelTituloFinal)))
                .addContainerGap(30, Short.MAX_VALUE))
            .addComponent(jSeparator1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(imgLogotipo, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imgBola1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(labelTitulo1)))
                .addGap(18, 18, 18)
                .addComponent(boxParaChoques, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imgBola2)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(labelTitulo2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(boxTetos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imgBola3)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(labelTitulo3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(boxVidros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imgBola4)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(labelTitulo4)))
                .addGap(18, 18, 18)
                .addComponent(boxPneus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(boxJantes, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(labelTituloFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnSeguinte))
                .addGap(17, 17, 17))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void boxTetosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxTetosActionPerformed
        
        String escolha = (String) boxTetos.getSelectedItem();
        facade.escolheTetos(escolha);
    }//GEN-LAST:event_boxTetosActionPerformed

    private void boxVidrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxVidrosActionPerformed
        
        String escolha = (String) boxVidros.getSelectedItem();
        facade.escolheVidros(escolha);
    }//GEN-LAST:event_boxVidrosActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        frAnterior.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnSeguinteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeguinteActionPerformed
        // TODO add your handling code here:
        EfetuarPagamentoGUI nova = new EfetuarPagamentoGUI(this,facade);
        nova.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnSeguinteActionPerformed

    private void boxParaChoquesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxParaChoquesActionPerformed
        // TODO add your handling code here

        String escolha = (String) boxParaChoques.getSelectedItem();
        facade.escolheParaChoques(escolha);
    }//GEN-LAST:event_boxParaChoquesActionPerformed

    private void boxPneusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxPneusActionPerformed

        String escolha = (String) boxPneus.getSelectedItem();
        facade.escolhePneus(escolha);
    }//GEN-LAST:event_boxPneusActionPerformed

    private void boxJantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxJantesActionPerformed
        // TODO add your handling code here:
        String escolha = (String) boxJantes.getSelectedItem();
        facade.escolheJantes(escolha);
    }//GEN-LAST:event_boxJantesActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        frAnterior.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    
    private void predefinicoes() {
        boxJantes.setSelectedIndex(0);
        boxParaChoques.setSelectedIndex(0);
        boxPneus.setSelectedIndex(0);
        boxTetos.setSelectedIndex(0);
        boxVidros.setSelectedIndex(0);
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxJantes;
    private javax.swing.JComboBox<String> boxParaChoques;
    private javax.swing.JComboBox<String> boxPneus;
    private javax.swing.JComboBox<String> boxTetos;
    private javax.swing.JComboBox<String> boxVidros;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSeguinte;
    private javax.swing.JLabel imgBola1;
    private javax.swing.JLabel imgBola2;
    private javax.swing.JLabel imgBola3;
    private javax.swing.JLabel imgBola4;
    private javax.swing.JLabel imgLogotipo;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JLabel labelTitulo1;
    private javax.swing.JLabel labelTitulo2;
    private javax.swing.JLabel labelTitulo3;
    private javax.swing.JLabel labelTitulo4;
    private javax.swing.JLabel labelTituloFinal;
    // End of variables declaration//GEN-END:variables
}
