Querie a:
SELECT COUNT (ID_TITULO) FROM TITULO
Resposta: 49

Querie b:
SELECT COUNT (ID_MUSICA) FROM MUSICA
Resposta: 500

Querie c:
SELECT COUNT (ID_AUTOR) FROM AUTOR
Resposta: 213

Querie d:
SELECT DISTINCT COUNT (ID_EDITORA) FROM EDITORA
Resposta: 5

Querie e:
SELECT COUNT (ID_TITULO) FROM TITULO
    INNER JOIN AUTOR ON TITULO.ID_AUTOR=AUTOR.ID_AUTOR
    WHERE AUTOR.NOME='Max Changmin'
Resposta: 2

Querie f:
SELECT TITULO.TITULO FROM TITULO
    WHERE TITULO.DTA_COMPRA=to
Resposta: 

Querie g:
SELECT AUTOR.NOME FROM TITULO
    INNER JOIN AUTOR ON TITULO.ID_AUTOR=AUTOR.ID_AUTOR
    WHERE DTA_COMPRA=to_date('01-02-2010', 'dd-mm-yyyy') AND PRECO=12
Resposta: Yumi Yoshimura

Querie h:
SELECT EDITORA.NOME FROM TITULO
    INNER JOIN AUTOR ON TITULO.ID_AUTOR=AUTOR.ID_AUTOR
    INNER JOIN EDITORA ON TITULO.ID_EDITORA=EDITORA.ID_EDITORA
    WHERE DTA_COMPRA=to_date('01-02-2010', 'dd-mm-yyyy') AND PRECO=12
Resposta: EMI

Querie i:
SELECT DTA_REVIEW,CONTEUDO FROM REVIEW
    INNER JOIN TITULO ON REVIEW.ID_TITULO=TITULO.ID_TITULO
    WHERE TITULO.TITULO='oh whoa oh'
Resposta:
07-MAY-17   EXCELENTE
24-MAY-16   EXCELENTE
24-JUL-17   EXCELENTE

Querie j:
SELECT DTA_REVIEW,CONTEUDO FROM REVIEW
    INNER JOIN TITULO ON REVIEW.ID_TITULO=TITULO.ID_TITULO
    WHERE TITULO.TITULO='pump'
    ORDER BY DTA_REVIEW ASC
Resposta:
12-JUL-14   EXCELENTE
04-JAN-15   OBRA PRIMA
01-FEB-16   PÉSIMO
24-SEP-18   PÉSIMO

Querie k:
SELECT AUTOR.NOME FROM AUTOR
    INNER JOIN MUSICA ON AUTOR.ID_AUTOR=MUSICA.ID_AUTOR
    INNER JOIN TITULO ON MUSICA.ID_TITULO=TITULO.ID_TITULO
    WHERE DTA_COMPRA=to_date('04-04-1970','dd-mm-yyyy') AND PRECO=20
Resposta:
Bruno Branco
Fiuk
Piret Järvis
Marisa Liz
Matt Cardle
Katy Perry
Ryan Tedder
Robbie Williams
Haeryung
Han Hye-ri

Querie l:
SELECT SUM(PRECO) FROM TITULO
    INNER JOIN EDITORA ON EDITORA.ID_EDITORA=TITULO.ID_EDITORA
    WHERE EDITORA.NOME='EMI'
Resposta: 104

Querie m:
SELECT * FROM (SELECT TITULO FROM TITULO WHERE PRECO=20 ORDER BY DTA_COMPRA ASC) WHERE ROWNUM=1
Resposta: woman

Querie n:
SELECT COUNT(ID_MUSICA) FROM MUSICA
    INNER JOIN TITULO ON MUSICA.ID_TITULO=TITULO.ID_TITULO
    INNER JOIN SUPORTE ON TITULO.ID_SUPORTE=SUPORTE.ID_SUPORTE
    WHERE SUPORTE.NOME='MP3'
Resposta: 71

Querie o:
SELECT COUNT(ID_MUSICA) FROM MUSICA
    INNER JOIN TITULO ON MUSICA.ID_TITULO=TITULO.ID_TITULO
    INNER JOIN SUPORTE ON TITULO.ID_SUPORTE=SUPORTE.ID_SUPORTE
    INNER JOIN GENERO ON TITULO.ID_GENERO=GENERO.ID_GENERO
    WHERE SUPORTE.NOME='MP3' AND GENERO.NOME='Pop Rock'
Resposta: 20

Querie p:
SELECT SUM(PRECO) FROM TITULO
    INNER JOIN SUPORTE ON TITULO.ID_SUPORTE=SUPORTE.ID_SUPORTE
    WHERE SUPORTE.NOME='Blue-Ray'
Resposta: 72

Querie q:
SELECT SUM(PRECO) FROM TITULO
    INNER JOIN SUPORTE ON TITULO.ID_SUPORTE=SUPORTE.ID_SUPORTE
    INNER JOIN EDITORA ON TITULO.ID_EDITORA=EDITORA.ID_EDITORA
    WHERE SUPORTE.NOME='Blue-Ray' AND EDITORA.NOME='EMI'
Resposta: 48

Querie r:
SELECT SUM(PRECO) FROM TITULO
Resposta: 503

Querie s:
SELECT NOME FROM
(SELECT EDITORA.NOME , SUM(PRECO) AS GastoTotal FROM TITULO 
    INNER JOIN EDITORA ON EDITORA.ID_EDITORA=TITULO.ID_EDITORA
    GROUP BY EDITORA.NOME
    ORDER BY GastoTotal DESC)
WHERE ROWNUM=1
Resposta: Apple

Querie t:
SELECT RES2.ID AS IDEditora, COUNT(TITULO.ID_TITULO) AS Titulos FROM 
(SELECT RES.ID FROM (
        SELECT EDITORA.ID_EDITORA AS ID, COUNT(TITULO.ID_TITULO) AS TitulosHeavyMetal FROM EDITORA 
        INNER JOIN TITULO ON TITULO.ID_EDITORA=EDITORA.ID_EDITORA
        INNER JOIN GENERO ON GENERO.ID_GENERO=TITULO.ID_GENERO
        WHERE GENERO.NOME='Heavy Metal' 
        GROUP BY EDITORA.ID_EDITORA
        ORDER BY TitulosHeavyMetal DESC
) RES
WHERE ROWNUM = 1) RES2
INNER JOIN TITULO ON TITULO.ID_EDITORA = RES2.ID
GROUP BY RES2.ID
Resposta: